---
- name: Orchestrate Python scripts for parsing and report generation
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/correction_vars.yml

  tasks:
    - name: Vérifier que le répertoire source existe
      stat:
        path: "{{ source_dir }}"
      register: source_dir_check

    - name: Arrêter si le répertoire source est manquant
      fail:
        msg: "Le répertoire source {{ source_dir }} est introuvable."
      when: not source_dir_check.stat.exists

    - name: Execute the parsing script
      command: >
        python3 {{ script_dir }}/parse_unl.py
        --source-dir {{ source_dir }}
        --output-dir {{ parsed_dir }}
      register: parse_output
    - debug:
        msg: "{{ parse_output.stdout }}"

    - name: Ensure solution JSON file exists after parsing
      stat:
        path: "{{ solution_file }}"
      register: solution_file_check

    - name: Fail if solution JSON file is missing
      fail:
        msg: "Solution JSON file {{ solution_file }} was not generated by the parsing script."
      when: not solution_file_check.stat.exists

    - name: Execute the report generation script
      command: >
        python3 {{ script_dir }}/generate_report.py
        --parsed-dir {{ parsed_dir }}
        --output-dir {{ reports_dir }}
        --solution-file {{ solution_file }}
      register: report_output
    - debug:
        msg: "{{ report_output.stdout }}"
